version: '3.3'
services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql-db
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'griffo_setup'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_USER: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./infra:/docker-entrypoint-initdb.d/  
    networks:
      - default
  app:
    environment:      # env vars
        DB_HOST: 
    build:
      context: . #indica o dir da Dockerfile
      dockerfile: Dockerfile-api

# Names our volume
volumes: 
  mysql-volume: